# Generated by Django 3.2.6 on 2022-03-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_filters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filters',
        ),
    ]
