# Generated by Django 3.2.6 on 2022-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
