# Generated by Django 3.2.6 on 2022-03-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sname',
        ),
    ]
