# Generated by Django 3.2.6 on 2022-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui',
            name='video',
            field=models.FileField(default='', upload_to='uploads/video/'),
        ),
        migrations.AlterField(
            model_name='ui',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/ui/'),
        ),
    ]
